# Generated by Django 2.0 on 2018-10-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='org',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telephone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=50, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stu_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='学号'),
        ),
    ]
