# Generated by Django 2.0 on 2018-10-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181023_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, default='未知', max_length=128, verbose_name='姓名'),
        ),
    ]
