# Generated by Django 2.0 on 2018-10-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_paper_clicked_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='clicked_num',
        ),
    ]
